# Generated by Django 2.0 on 2020-03-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qnty',
        ),
    ]
